[package]
name = "chess_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-derive = "0.2"
num-traits = "0.2"
log = "0.4.17"
tokio = { version = "1", features = ["full"] }